version: '3.8'

services:

  api:
    build: .
    image: api
    container_name: api
    ports:
      - 5004:5000
      - 5005:5001
    command: bash start.sh
    user: app
    volumes:
      - .:/usr/src/app
    environment:
      - APP_SETTINGS=config.BaseConfig
    depends_on:
      - redis

  worker:
    image: api
    build: .
    command: python manage.py run_worker
    volumes:
      - .:/usr/src/app
    environment:
      - APP_SETTINGS=config.BaseConfig
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine


